// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmy87kts4OO-uhaiNxTlt_mpXPE-NKRb8',
    appId: '1:990218908789:web:28f2d0c4930a61199af43c',
    messagingSenderId: '990218908789',
    projectId: 'education-all-in-one',
    authDomain: 'education-all-in-one.firebaseapp.com',
    databaseURL: 'https://education-all-in-one-default-rtdb.firebaseio.com',
    storageBucket: 'education-all-in-one.firebasestorage.app',
    measurementId: 'G-GWVBQTCD4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_YbwleKv_MEYFuqC4NbbXCcrsFk_KkQ',
    appId: '1:990218908789:android:e7557b737c74231d9af43c',
    messagingSenderId: '990218908789',
    projectId: 'education-all-in-one',
    databaseURL: 'https://education-all-in-one-default-rtdb.firebaseio.com',
    storageBucket: 'education-all-in-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnd0AdcDdogkdOP1ijFdYVPqpbCeErXIw',
    appId: '1:990218908789:ios:c2f7c4db1f0556909af43c',
    messagingSenderId: '990218908789',
    projectId: 'education-all-in-one',
    databaseURL: 'https://education-all-in-one-default-rtdb.firebaseio.com',
    storageBucket: 'education-all-in-one.firebasestorage.app',
    iosBundleId: 'com.example.luyipWebsiteEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnd0AdcDdogkdOP1ijFdYVPqpbCeErXIw',
    appId: '1:990218908789:ios:c2f7c4db1f0556909af43c',
    messagingSenderId: '990218908789',
    projectId: 'education-all-in-one',
    databaseURL: 'https://education-all-in-one-default-rtdb.firebaseio.com',
    storageBucket: 'education-all-in-one.firebasestorage.app',
    iosBundleId: 'com.example.luyipWebsiteEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmy87kts4OO-uhaiNxTlt_mpXPE-NKRb8',
    appId: '1:990218908789:web:8e9657567a0f64319af43c',
    messagingSenderId: '990218908789',
    projectId: 'education-all-in-one',
    authDomain: 'education-all-in-one.firebaseapp.com',
    databaseURL: 'https://education-all-in-one-default-rtdb.firebaseio.com',
    storageBucket: 'education-all-in-one.firebasestorage.app',
    measurementId: 'G-WJFK0ERER6',
  );
}
